### ISSUE TITLE
Files missed in /apollo/cyber/carla_bridge/carla_proto/proto.

### ISSUE THREAD

**Issue by JohannesLiu** [casper-auto/carla-apollo#1]
Hello, 

I'm currently testing Carla with apollo using your repository. However, I encounter problems when running the bridge.py and carla_spawn_object.py. 

![image](https://user-images.githubusercontent.com/21165057/164413305-64999f38-f99e-4c72-9136-89d411eeac76.png)

As you can see, when I run the script "python carla_cyber_bridge/bridge.py" and "python carla_spawn_object/carla_spawn_object.py". It informs me some files are missed. 

I make sure I have compiled Apollo with ./apollo.sh build_gpu.

I want to know if there is something missed?

My OS is Ubuntu 20.04 with nvidia-docker.

**Comment by yuting-fu** [comment]
Hi, for the first error msg you see, you need to rebuild cyber, not Apollo inside the docker. I have the same situation. Just follow the instruction, $ rm -rf /root/.cache/..., then $ ./apollo.sh build_cyber opt
Then you should be able to run the two scripts. Apollo is built and ran from a separate container. I'm using the one from AuroAi.

**Comment by JohannesLiu** [comment]
> Hi, for the first error msg you see, you need to rebuild cyber, not Apollo inside the docker. I have the same situation. Just follow the instruction, $ rm -rf /root/.cache/..., then $ ./apollo.sh build_cyber opt Then you should be able to run the two scripts. Apollo is built and ran from a separate container. I'm using the one from AuroAi.

Hi yuting. I really appreciate your help. Now, I have run the scripts successfully. However, I found that the dreamviewer cannot display the normal simulation information. 


![image](https://user-images.githubusercontent.com/21165057/164448684-f7d96dd6-e38f-46e4-a661-a17e4785d1f1.png)

As you can see. The apollo cannot connect to Carla. Could you help me with it?

I used the Apollo 5.0 from AuroAI as you too.  In addition, I set the CYBER_IP (/apollo/cyber/setup.bash) in carla-cyber container to 172.17.0.15, which is the carla-cyber's IP in the host. 
 I've followed the steps, which this tutorial does not talk about,  from this repository https://github.com/AuroAi/carla_apollo_bridge.

I also watched the presentation from https://www.bilibili.com/video/BV1Vq4y1b7E7/. And I tried to run a local Carla instead of the docker version of Carla as the video shown. But the apollo can still not be connected to Carla.  I really need your help.

**Comment by yuting-fu** [comment]
Hi Johannes, we run Carla 0.9.11 from a docker container. The Apollo we use is from [AuroAi/apollo](https://github.com/AuroAi/apollo) and set the CYBER_IP in the same way as you did. Did you source the ~/.bashrc after changing the CYBER_IP?
In our case, dreamview will connect as soon as the spawn objects script is running. BTW, we also built apollo with build_opt_gpu instead of build_opt.

**Comment by JohannesLiu** [comment]
> Hi Johannes, we run Carla 0.9.11 from a docker container. The Apollo we use is from [AuroAi/apollo](https://github.com/AuroAi/apollo) and set the CYBER_IP in the same way as you did. Did you source the ~/.bashrc after changing the CYBER_IP? In our case, dreamview will connect as soon as the spawn objects script is running.

Hi, Yuting. I run the same Carla version as yours. I have sourced ~/.bashrc.  And I built apollo with build_gpu. It seems all steps are right. I think I should reboot the machine and perform all the operations again to make sure there is no error. 
I think I'm approaching success. Thank you very much!

**Comment by JohannesLiu** [comment]
> > Hi Johannes, we run Carla 0.9.11 from a docker container. The Apollo we use is from [AuroAi/apollo](https://github.com/AuroAi/apollo) and set the CYBER_IP in the same way as you did. Did you source the ~/.bashrc after changing the CYBER_IP? In our case, dreamview will connect as soon as the spawn objects script is running.
> 
> Hi, Yuting. I run the same Carla version as yours. I have sourced ~/.bashrc. And I built apollo with build_gpu. It seems all steps are right. I think I should reboot the machine and perform all the operations again to make sure there is no error. I think I'm approaching success. Thank you very much!

Hi, Yuting. Thank you very much! I have run the simulation successfully. After I set a point on the route map, I can see the the planning trajectory. However, I watched the car cannot move, even I turned on the control button on the module controller panel. 
![image](https://user-images.githubusercontent.com/21165057/164455126-9b7055a8-2b30-494f-bb58-ab134ba58f4c.png)

Could you please give me some suggestions? Thanks again!

**Comment by yuting-fu** [comment]
If you disable and enable control again, the car will move forward for a very short distance, then go off road and stop. That's the current status we are in. It's also the same issue as mentioned at the end of the demo video.

**Comment by JohannesLiu** [comment]
> If you disable and enable control again, the car will move forward for a very short distance, then go off road and stop. That's the current status we are in. It's also the same issue as mentioned at the end of the demo video.

Thank you very much for helping me. It seems that this bug hinders the promotion of Apollo with Carla. I noticed the similar problem existed in another repository.  What a pity.  Anyway, thank you very much. Wish you a good day.

**Comment by torgeros** [comment]
The problem with the `spawn_objects` script is, that the tutorial has a typo. It is `spawn_objects`, not `spawn_object` (with an 's')!

I have opened #6 to fix this.
