### ISSUE TITLE
Error when executing the lines for "terminal 1" carla_cyber_bridge/bridge.py

### ISSUE THREAD

**Issue by RubenAndServin** [casper-auto/carla-apollo#2]
Hello, I get the following error and I don't understand what it is and what I might be doing wrong. I am running Apollo from AuroAi . And following these steps I get no problems up to this point. what is going on? Thank you very much.

![image](https://user-images.githubusercontent.com/99920593/165402093-091d1643-fb6d-464b-a343-9ff5a38cb18c.png)

**Comment by xpharry** [comment]
I should update the instruction later. Sorry for that.

The error is because the newly added carla_proto was not built yet.

In the carla-apollo docker container, run `$ ./apollo.sh build_py` to build the module. Then it would be fine.

**Comment by RubenAndServin** [comment]
When I do that I get the following: 
![image](https://user-images.githubusercontent.com/99920593/165629558-10d59888-49a8-422a-a27d-d3054d3da270.png)

**Comment by xpharry** [comment]
Did you try

```
cd /apollo/cyber/carla_bridge
python carla_cyber_bridge/bridge.py
```

as instructed?

**Comment by RubenAndServin** [comment]
> Has probado
> 
> ```
> cd /apollo/cyber/carla_bridge
> python carla_cyber_bridge/bridge.py
> ```
> 
> ¿como se indica?

**Comment by RubenAndServin** [comment]
Sorry, I was editing it because I got confused in the screenshot.

**Comment by xpharry** [comment]
In the screenshot, you were not under the path I suggested. Right?

**Comment by RubenAndServin** [comment]
Sorry xpharry for these misunderstandings. Indeed, I was not on the route you suggested. I'm going in order, following what you suggested:

![image](https://user-images.githubusercontent.com/99920593/165632908-d89f52c3-52ce-4c7a-8e95-7f04e7142f7a.png)

**Comment by xpharry** [comment]
Did you start the carla simulator first?

**Comment by RubenAndServin** [comment]
Wow, this is all because I'm just getting started in this. Sorry for the obviousness. This is done by downloading the CARLA 0.9.11 image and booting before? Now I realize that in AuroAi you do this for "docker run --gpus=all --name=carla-server --net=host -d carlasim/carla:0.9.6" but for the version you use?
